spring:
  datasource:
    username: root
    password: 1234
    mapper-locations: classpath:/mapper/**/*.xml
    url: jdbc:mysql://localhost:3306/spending?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true



mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.zzdd.smallspending.*

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
